REPORT ZFEBCLASSICAL_REPORT LINE-COUNT 15(2).

TABLES: MARA.

TYPES: BEGIN OF STR_MARA,
        MATNR TYPE MARA-MATNR,
        ERSDA TYPE MARA-ERSDA,
        ERNAM TYPE MARA-ERNAM,
        MTART TYPE MARA-MTART,
        MBRSH TYPE MARA-MBRSH,
      END OF STR_MARA.

DATA: IT_MARA TYPE TABLE OF STR_MARA,
      WA_MARA TYPE STR_MARA.

*
*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: P_MATNR FOR MARA-MATNR.
PARAMETERS:     P_MTART TYPE MARA-MTART.
SELECTION-SCREEN END OF BLOCK B1.

INITIALIZATION.
P_MATNR-LOW = '000000000000000023'.
P_MATNR-HIGH = '000000000000000078'.
P_MATNR-SIGN = 'E'.
P_MATNR-OPTION = 'BT'.
APPEND P_MATNR.

AT SELECTION-SCREEN.
  IF P_MTART = 'ROH'.
    MESSAGE 'YOU ARE NOT AUTHORZIED PERSON TO CREATE MATERIAL ROH, PLEASE SELECT OTHER TYPE' TYPE 'E'.
  ENDIF.


TOP-OF-PAGE.
WRITE: 'MATERIAL NO' COLOR 5,
       30 'DATE' COLOR 4,
       50'USER NAME' COLOR 7,
       70 'MAT TYPE',
       90 'IND SECTOR'.
ULINE.

END-OF-PAGE.
WRITE 'THIS IS FOOTER'.

START-OF-SELECTION.
       SELECT
       MATNR
       ERSDA
       ERNAM
       MTART
       MBRSH
       FROM MARA INTO TABLE IT_MARA
       WHERE MATNR IN P_MATNR OR MTART NE 'ROH'.


LOOP AT IT_MARA INTO WA_MARA.
  WRITE:/ WA_MARA-MATNR,
         30 WA_MARA-ERSDA COLOR 4,
         50 WA_MARA-ERNAM,
         70 WA_MARA-MTART,
         90 WA_MARA-MBRSH.
ENDLOOP.
