REPORT ZFEBCLASSICAL_REPORT2.

TABLES: MARA, MAKT, MARC.

TYPES: BEGIN OF STR_MARA,
        MATNR TYPE MARA-MATNR,
        MTART TYPE MARA-MTART,
        MBRSH TYPE MARA-MBRSH,
        MATKL TYPE MARA-MATKL,
        MEINS TYPE MARA-MEINS,
*        MAKTX TYPE MAKT-MAKTX,
*        WERKS TYPE MARC-WERKS,
      END OF STR_MARA.

TYPES: BEGIN OF STR_MAKT,
      MATNR TYPE MAKT-MATNR,
      MAKTX TYPE MAKT-MAKTX,
     END OF STR_MAKT.

DATA: IT_MARA TYPE TABLE OF STR_MARA,
      WA_MARA TYPE STR_MARA,
      IT_MAKT TYPE TABLE OF STR_MAKT,
      WA_MAKT TYPE STR_MAKT.

SELECT-OPTIONS: P_MATNR FOR MARA-MATNR.

TOP-OF-PAGE.
WRITE: 'MAT NO',
       30 'MAT TYPE',
       50 'IND SECTOR',
       60 'MAT GRUP',
       70 'UNIT',
       80 'DISC',
       100 'PLANT'.
ULINE.

START-OF-SELECTION.
*     SELECT
*      MARA~MATNR
*      MTART
*      MBRSH
*      MATKL
*      MEINS
*      MAKT~MAKTX
*      MARC~WERKS
*      FROM MARA INNER JOIN MAKT ON MARA~MATNR = MAKT~MATNR
*                INNER JOIN MARC ON MARA~MATNR = MARC~MATNR
*      INTO TABLE IT_MARA
*      WHERE MARA~MATNR IN P_MATNR.

      SELECT
       MATNR
       MTART
       MBRSH
       MATKL
       MEINS
       FROM MARA INTO TABLE IT_MARA
       WHERE MATNR IN P_MATNR.

*  IF IT_MARA IS NOT INITIAL.
*  SELECT MATNR MAKTX FROM MAKT INTO TABLE IT_MAKT WHERE MATNR = P_MATNR.
*  ENDIF.

  LOOP AT IT_MARA INTO WA_MARA.

  SELECT SINGLE MATNR MAKTX FROM MAKT INTO WA_MAKT WHERE MATNR = WA_MARA-MATNR.
*    READ TABLE IT_MAKT INTO WA_MAKT WITH KEY MATNR = WA_MARA-MATNR.

    WRITE: / WA_MARA-MATNR,
            30 WA_MARA-MTART,
            50 WA_MARA-MBRSH,
            60 WA_MARA-MEINS,
            70 WA_MARA-MATKL,
            80 WA_MAKT-MAKTX.

  ENDLOOP.
